#端口
server:
  port: 9090

#消费端配置
eureka:
  client:   #将客户端注册到 eureka 服务列表内
    service-url:
      #将服务注册到 Eureka 集群
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      #注册表抓取间隔
      registry-fetch-interval-seconds: 30
      instance:
        #心跳检测配置
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90

spring:
  application:
    name: eureka-consumer   #微服务名称，对外暴漏的微服务名称，十分重要
